language: python
python:
  - "3.6" # current default Python on Travis CI
  - "3.7"
  - "3.8"
install:
  - pip install codecov
script:
  - coverage run -m unittest discover tests/
after_success:
  - codecov
